services:
  postgres:
    image: postgres
    container_name: postgres-container
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./postgres/.env
    restart: unless-stopped

  django:
    build:
      context: ./tasks-api
    container_name: django-container
    ports:
      - 8000:8000
    env_file:
      - ./tasks-api/.env
    volumes:
      - /var/static:/app/static
      - /var/media:/app/media
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
  postgres_data:
